enableColors: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0076
    level: discard

nodeLinker: node-modules

npmPublishAccess: public

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.1.1.cjs
