nodeLinker: pnp

npmPublishAccess: public

# npmRegistryServer: "http://localhost:4873/"
# unsafeHttpWhitelist:
#   - localhost

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

pnpFallbackMode: all

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.1.1.cjs
